services:
  php:
    container_name: invoiceshelf-dev-php
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      target: development
    ports:
      - "80:8080"
    environment:
      - PUID=${USRID:-1000}
      - PGID=${GRPID:-1000}
      - AUTORUN_ENABLED=true   # lets the image run composer/migrations etc
    volumes:
      - ../../:/var/www/html
      # - vendor:/var/www/html/vendor  # vendor lives in Docker, not on host
    # networks:
    #   - invoiceshelf-dev

  node:
    container_name: invoiceshelf-dev-node
    image: node:20-alpine
    working_dir: /var/www/html
    volumes:
      - ../../:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "yarn && yarn dev"
    networks:
      - invoiceshelf-dev

  datasette:
    image: datasetteproject/datasette
    restart: unless-stopped
    ports:
      - "8080:8001"
    volumes:
      - ../../storage/app:/data
    user: root
    command: datasette --host 0.0.0.0 /data/database.sqlite

  # mail:
  #   container_name: invoiceshelf-dev-mailpit
  #   image: axllent/mailpit:latest
  #   ports:
  #     - '1025:1025'
  #     - '8025:8025'
  #   networks:
  #     - invoiceshelf-dev

networks:
  invoiceshelf-dev:

# volumes:
#   vendor:
