services:
  php:
    container_name: invoiceshelf-dev-php
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      target: development
    ports:
      - "80:8080"
    environment:
      - PUID=${USRID:-1000}
      - PGID=${GRPID:-1000}
      - AUTORUN_ENABLED=true   # lets the image run composer/migrations etc
    volumes:
      - ../../:/var/www/html
      # - vendor:/var/www/html/vendor  # vendor lives in Docker, not on host
    # networks:
    #   - invoiceshelf-dev

  adminer:
    container_name: invoiceshelf-dev-adminer
    build:
      context: ../../
      dockerfile: docker/development/adminer/Dockerfile
    environment:
      ADMINER_PLUGINS: tables-filter
      ADMINER_DESIGN: konya
    volumes:                                                                              
      - ../../database:/database
    ports:
      - '8080:8080'
    networks:
      - invoiceshelf-dev

  # mail:
  #   container_name: invoiceshelf-dev-mailpit
  #   image: axllent/mailpit:latest
  #   ports:
  #     - '1025:1025'
  #     - '8025:8025'
  #   networks:
  #     - invoiceshelf-dev

networks:
  invoiceshelf-dev:

# volumes:
#   vendor:
