#-------------------------------------------
# InvoiceShelf SQLite docker-compose variant
# Repo : https://github.com/InvoiceShelf/docker
#-------------------------------------------

services:
  webapp:
    container_name: invoiceshelf-variant-sqlite
    image: ghcr.io/harismu/invoiceshelfapp:latest
    ports:
      - "127.0.0.1:3001:8080" # 3001 is the port used in nginx
    volumes:
      - invoiceshelf_storage:/var/www/html/storage
    networks:
      - invoiceshelf
    environment:
      - APP_NAME=InvoiceShelf
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://fenixinvoice.duckdns.org
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/storage/app/database.sqlite # please don't touch this!
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=240
      - SESSION_DOMAIN=fenixinvoice.duckdns.org
      - SANCTUM_STATEFUL_DOMAINS=fenixinvoice.duckdns.org
    restart: unless-stopped
networks:
  invoiceshelf:
volumes:
  invoiceshelf_storage:
